server { 
    listen 80;#Port 80 listen
     server_name localhost; #Sever name for localhost
     oot /usr/share/nginx/html; #setting root directory
     index index.html index.htm; #index files
     
     
     location / {
         try_files $uri $uri/ =404;
          } }