name: Test with Atlas (Real DB)


on: 
   push: 
     branches: ["Florence-branch", "Chanon-brnach","Kunal-branch"] #Testing only to branches 
   pull_request: #on pull-request push to the  main branch
    branches: ["main"] 

#Jobs inside Github Actions Workflow to do automate testing
jobs:
  test:
    #Environment for testing
    runs-on: ubuntu-latest
    #Step 1: Checkout code from Github
    steps:
      - uses: actions/checkout@v4
      #Setp2: Setup environment for Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.9'
        
        #Python Check and install requirements and dependencies
      - name: Install
        run: pip install -r backend/requirements.txt pytest pymongo httpx uvicorn
        
        #FastAPI and Mongdob Atlas Testing
      - name: Test FastAPI + Atlas
        env:
            #Add Mongodb URL inside Secrets Github!
            MONGODB_URL: ${{ secrets.ATLAS_URI }}  # mongodb+srv://username:password
        #Commands to run backend  and API endpoints
        run: |
          cd backend
          uvicorn app:app --host 0.0.0.0 --port 8000 & 
          sleep 5
          python -c "
            import httpx, time
            time.sleep(3)
            r = httpx.get('http://0.0.0.0:8000/health'); print('Health:', r.json())
            r = httpx.post('http://0.0.0.0:8000/test-mongo'); print('Atlas:', r.json())
          "
        #Final docker build for frontend to ensure that it works with backend,Atlas,API
      - name: Frontend Docker
        run: docker build -t test ./frontend/ && echo "✅ All pass!"